workflows:
  flutter-release:
    name: Flutter Android and iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    integrations:
      app_store_connect: Codemagic

    scripts:
      - name: Flutter packages
        script: flutter pub get

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files \
            "com.carpiorenzo.tryingflutter" \
            --type IOS_APP_STORE \
            --create

      - name: Apply signing
        script: |
          xcode-project use-profiles

      - name: Build Android
        script: flutter build apk --release

      - name: Build iOS
        script: flutter build ipa --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/ipa/*.ipa
